#!/usr/bin/env node
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'
import fs from 'fs'
import crypto from 'crypto'
import readline from 'readline'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const rootDir = dirname(__dirname)

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
})

const question = (query) => new Promise((resolve) => rl.question(query, resolve))

const generateSecret = (length = 32) => {
  return crypto.randomBytes(length).toString('hex')
}

const setupEnvironment = async () => {
  console.log('===================================')
  console.log('   ENVIRONMENT SETUP TOOL')
  console.log('===================================\n')
  
  console.log('This will create/update your .env file with required settings.\n')
  
  const envPath = join(rootDir, '.env')
  let envContent = ''
  
  // Check if .env exists
  if (fs.existsSync(envPath)) {
    const backupPath = `${envPath}.backup-${Date.now()}`
    fs.copyFileSync(envPath, backupPath)
    console.log(`📁 Backup created: ${backupPath}`)
    envContent = fs.readFileSync(envPath, 'utf8')
  }
  
  // Default values
  const defaults = {
    // MongoDB
    MONGODB_URI: 'mongodb://localhost:27017/clean_street',
    
    // Server
    PORT: '5000',
    NODE_ENV: 'development',
    SESSION_SECRET: generateSecret(),
    
    // Frontend URLs
    FRONTEND_URL: 'http://localhost:3000',
    ADMIN_FRONTEND_URL: 'http://localhost:3000/admin',
    
    // SMTP (Gmail example)
    SMTP_HOST: 'smtp.gmail.com',
    SMTP_PORT: '587',
    SMTP_USER: '',
    SMTP_PASSWORD: '',
    SMTP_FROM: '',
    
    // Admin Setup
    ADMIN_EMAIL: 'superadmin@cleanstreet.com',
    ADMIN_PASSWORD: generateSecret(12),
    ADMIN_NAME: 'System Administrator',
    ADMIN_SETUP_KEY: generateSecret(),
    MASTER_SETUP_KEY: generateSecret(),
    
    // Security
    FORCE_PASSWORD_CHANGE: 'true',
    ENABLE_SUPER_ADMIN_2FA: 'false',
    
    // Google OAuth
    GOOGLE_CLIENT_ID: '',
    GOOGLE_CLIENT_SECRET: '',
    GOOGLE_CALLBACK_URL: 'http://localhost:5000/api/auth/google/callback'
  }
  
  console.log('Configure environment variables (press Enter for default):\n')
  
  const envVars = {}
  
  for (const [key, defaultValue] of Object.entries(defaults)) {
    let value = defaultValue
    
    // Special prompts for certain fields
    if (key === 'SMTP_PASSWORD') {
      console.log(`\n⚠️  For Gmail, use "App Password" not your regular password`)
      console.log(`   Generate at: https://myaccount.google.com/apppasswords`)
    }
    
    if (key === 'FORCE_PASSWORD_CHANGE' || key === 'ENABLE_SUPER_ADMIN_2FA') {
      const answer = await question(`${key} (true/false) [${defaultValue}]: `)
      value = answer.trim() || defaultValue
      if (!['true', 'false'].includes(value.toLowerCase())) {
        value = defaultValue
      }
    } else {
      const answer = await question(`${key} [${defaultValue}]: `)
      value = answer.trim() || defaultValue
    }
    
    envVars[key] = value
  }
  
  // Build .env content
  let newEnvContent = '# Clean Street Environment Variables\n'
  newEnvContent += '# Generated by setup tool\n'
  newEnvContent += `# ${new Date().toISOString()}\n\n`
  
  for (const [key, value] of Object.entries(envVars)) {
    newEnvContent += `${key}=${value}\n`
  }
  
  // Write .env file
  fs.writeFileSync(envPath, newEnvContent)
  
  console.log('\n' + '='.repeat(50))
  console.log('✅ ENVIRONMENT SETUP COMPLETE')
  console.log('='.repeat(50))
  console.log(`📁 File created: ${envPath}`)
  console.log('\n⚠️  IMPORTANT: Review your .env file for correctness!')
  
  // Check for common issues
  console.log('\n🔍 Configuration check:')
  
  if (envVars.SMTP_USER && !envVars.SMTP_PASSWORD) {
    console.log('❌ SMTP password is empty but SMTP user is set')
  }
  
  if (envVars.ADMIN_PASSWORD.length < 8) {
    console.log('❌ ADMIN_PASSWORD is too short (min 8 characters)')
  }
  
  if (envVars.ADMIN_SETUP_KEY === defaults.ADMIN_SETUP_KEY) {
    console.log('⚠️  ADMIN_SETUP_KEY is using default - change for production')
  }
  
  console.log('\n🚀 Next steps:')
  console.log('1. Run MongoDB: mongod (if not running)')
  console.log('2. Create super admin: npm run create-super-admin')
  console.log('3. Start server: npm run dev')
  console.log('4. Visit: http://localhost:5000/api/system/status')
  
  rl.close()
}

setupEnvironment().catch(error => {
  console.error('Error:', error.message)
  process.exit(1)
})